# Generated by Django 3.2.8 on 2021-10-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plan_app', '0001_initial'),
        ('recipe_app', '0002_auto_20211006_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ManyToManyField(related_name='shopping_list_ingredient', to='recipe_app.Ingredient')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_meal_plan', to='meal_plan_app.mealplan')),
                ('tools', models.ManyToManyField(related_name='shopping_list_tools', to='recipe_app.Tool')),
            ],
        ),
    ]
