# Generated by Django 3.2.8 on 2021-10-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0002_shoppinglist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
