# Generated by Django 3.2.8 on 2021-10-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0003_rename_ingredient_shoppinglist_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
