# Generated by Django 3.2.8 on 2021-10-11 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(default=None, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_created_by', to=settings.AUTH_USER_MODEL)),
                ('friday', models.ManyToManyField(related_name='friday_recipe', to='recipe_app.Recipe')),
                ('monday', models.ManyToManyField(related_name='monday_recipe', to='recipe_app.Recipe')),
                ('saturday', models.ManyToManyField(related_name='saturday_recipe', to='recipe_app.Recipe')),
                ('sunday', models.ManyToManyField(related_name='sunday_recipe', to='recipe_app.Recipe')),
                ('thursday', models.ManyToManyField(related_name='thursday_recipe', to='recipe_app.Recipe')),
                ('tuesday', models.ManyToManyField(related_name='tuesday_recipe', to='recipe_app.Recipe')),
                ('wednesday', models.ManyToManyField(related_name='wednesday_recipe', to='recipe_app.Recipe')),
            ],
        ),
    ]
