# Generated by Django 3.2.8 on 2021-10-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
