# Generated by Django 3.2.8 on 2021-10-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_day',
        ),
    ]
