# Generated by Django 3.2.8 on 2021-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isDarkMode',
            field=models.BooleanField(default=False),
        ),
    ]
