# Generated by Django 3.2.8 on 2021-10-06 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0004_rename_measurement_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe_favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='owned_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='tool_owned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
