# Generated by Django 3.2.8 on 2021-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
