# Generated by Django 3.2.8 on 2021-10-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_auto_20211014_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
