# Generated by Django 3.2.8 on 2021-10-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_app', '0004_delete_shoppinglist'),
        ('recipe_app', '0011_rename_instruction_recipe_instructions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
